const SET_USER = 'SET_USER';
const REMOVE_USER = 'REMOVE_USER';
const SET_LOGGED_USER = 'SET_LOGGED_USER';
const REMOVE_LOGGED_USER = 'REMOVE_LOGGED_USER';

export { SET_USER, REMOVE_USER, SET_LOGGED_USER, REMOVE_LOGGED_USER };
