const SET_USER = 'SET_USER';
const REMOVE_USER = 'REMOVE_USER';
const SET_PARTIES = 'SET_PARTIES';
const SET_LOGGED_USER = 'SET_LOGGED_USER';
const REMOVE_LOGGED_USER = 'REMOVE_LOGGED_USER';

export {
  SET_USER,
  REMOVE_USER,
  SET_PARTIES,
  SET_LOGGED_USER,
  REMOVE_LOGGED_USER,
};
